### ISSUE TITLE
Incorrect information in Precompiled v1.1.1 wiki page

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#1055]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am not running a deprecated version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

The wiki page https://github.com/privacy-scaling-explorations/maci/wiki/Precompiled-v1.1.1 needs to be updated

- The 3rd param for Vote Tallying should be voteOptionTreeDepth as opposed to `Message batch tree depth` (https://github.com/privacy-scaling-explorations/maci/blob/dev/circuits/circom/tallyVotes.circom#L18)

- StateTreeDepth for TallyVotes_6-3-3 should be 6, not 7.

# Current Behavior

What is the current behavior?

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- MACI version:
- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ctrlc03** [comment]
Please start referring to the documentation website for any up to data information about MACI. We will remove content from the wiki so that it is all kept up to date on maci.pse.dev 

You can refer to https://maci.pse.dev/docs/circuits#tally-votes-tallyvotes for tally specific params, and for all other params. 

We will update https://maci.pse.dev/docs/testing#vote-tallying as it was copied from the wiki - thanks for reporting
