### ISSUE TITLE
Docker issue with Apple M1

### ISSUE THREAD

**Issue by corwintines** [privacy-scaling-explorations/maci#333]
Running into this error on M1 Macbook air when running `./scripts/buildSnarks32.sh`:

root@ba313517a8a8:/maci/circuits# ./scripts/buildSnarks32.sh
Building batchUpdateStateTree_32
Compiling circom/prod/batchUpdateStateTree_32.circom...
Generated params/batchUst32.r1cs
Error: exec: /usr/bin/ld: /maci/circuits/params/fr.o: Relocations in generic ELF (EM: 62)
/usr/bin/ld: /maci/circuits/params/fr.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
at Object.error (/maci/circuits/node_modules/shelljs/src/common.js:110:27)
at execSync (/maci/circuits/node_modules/shelljs/src/exec.js:102:12)
at Object._exec (/maci/circuits/node_modules/shelljs/src/exec.js:205:12)
at Object.exec (/maci/circuits/node_modules/shelljs/src/common.js:335:23)
at main (/maci/circuits/build/buildSnarks.js:116:15)
at Object.<anonymous> (/maci/circuits/build/buildSnarks.js:138:20)
at Module._compile (node:internal/modules/cjs/loader:1108:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
at Module.load (node:internal/modules/cjs/loader:973:32)
at Function.Module._load (node:internal/modules/cjs/loader:813:14)

**Comment by corydickson** [comment]
What version of `gcc` are you using?

**Comment by yuetloo** [comment]
I got the same error as well running on Apple M1, docker with ubuntu 21.04, using the docker file from the master branch of this project.

gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

**Comment by corydickson** [comment]
Don't have an M1 to test myself but will address this if I can get my hands on one. In my environment though I am using  gcc>=11...

Anecdotally I've heard some success of M1 mac users being able to build the circuits using clang if you're willing to hack for a solution

**Comment by corydickson** [comment]
could you share your gcc configuration as well just to compare the flags?

**Comment by yuetloo** [comment]
Did you manually build the circuits on your machine or use the Dockerfile in this project?  The gcc installed using the Dockerfile is 10.3.0.

Here's the output of the gcc installed in the container running on my macbook.  (I used `docker buildx build --platform linux/arm64` to build the image instead of just docker build and the result is the same either way)


```
root@9b3f2ec3962f:/maci/circuits# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/10/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.3.0-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1)
```

I also setup an AWS linux ec2 instance and was able to build the circuit using the docker file, the gcc here looks similar to the above except that the target is x86_64-linux-gnu


I don't know if the issue is with docker or if there's something that can be adjusted in the docker file or how to build the docker image, but the following output looks odd to me.

```
root@9b3f2ec3962f:/maci/circuits# file /maci/circuits/params/fr.o
/maci/circuits/params/fr.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

**Comment by corydickson** [comment]
I have been manually building the circuits on my machine. My suspicion is that it may have something to do with `nasm` build target and static linked objects it generates. We could try doing an objdump and sharing the differences between the two files and reporting it to the maintainer of the circom compiler

**Comment by corydickson** [comment]
A little bit out of my depth for how the compiler works

**Comment by yuetloo** [comment]
I haven't built on my machine as I thought there might be dependencies on linux because the instructions on the readme are only on how to built on ubuntu.  If I try it later on my machine and have any success, I'll report it here. 
But, I did try building the docker image using buildx following this guide (https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/). I also tried using `arm64v8/ubuntu` as the base image.  Both attempts failed with the same error running the buildSnark32.sh script.
