### ISSUE TITLE
Scope out: Programmatically verify Ceremony was set up correctly

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#612]

**Comment by 0xjei** [comment]
This issue is intended to prevent this scenario: avoid failures if someone runs `contribute` right after the setup step. As a suggestion from @daodesigner: "a naive check would be to send only the first contribution".

The workflow after refactoring of `setup` command makes us able to cover this scenario:
- After successful execution of the `setup` command: ceremony and circuits are created on the Firestore DB, artifacts are ready in the ceremony bucket (S3), and the ceremony has the state "SCHEDULED".
- The ceremony starts when the `startDate` field is less than the server's actual timestamp: when this happens, a cloud function is triggered to switch the ceremony state from "SCHEDULED" to "OPENED".
- When running the `contribute` command, the user can see and select (and contribute) only those ceremonies with a status equal to "OPENED".

This assures that anyone (even if a coordinator) can only contribute to the ceremony when it has an `OPENED` status. In addition, the command `setup`:
- Verifies if the coordinator provides a correct pre-generated zKey by verifying the combination of PoT + R1CS + zKey. If invalid, the command generates the zKey from scratch and downloads a brand new PoT (avoiding using the corrupted zKey).
- It generates the genesis (= first) zKey (index 00000) for each ceremony circuit making the first participant (index 00001) comfy for contribution.

**Comment by gurrpi** [comment]
@0xjei 
Thanks for providing the context!
According to the sequence we designed at sprint planning, this issue describes a requirement that a Continuous ceremony pipeline should perform in the phase after https://github.com/privacy-scaling-explorations/maci/issues/618.

I've reflected the requirement of this issue in pseudo code of the ceremony pipeline: https://github.com/privacy-scaling-explorations/maci/blob/df37f2b567e04745c6645697147e85b7e637b3f8/.github/workflows/trigger-ceremony.yml#L25-L30

**Comment by 0xjei** [comment]
> According to the sequence we designed at sprint planning, this issue describes a requirement that a Continuous ceremony pipeline should perform in the phase after https://github.com/privacy-scaling-explorations/maci/issues/618.  I've reflected the requirement of this issue in pseudo code of the ceremony pipeline

Thank you @gurrpi for adding the issue motivation + pseudocode.

IMHO we could easily extract a set of conditions that should be satisfied in order to evaluate the correctness when setting up the ceremony after the ceremony pipeline setup trigger. The conditions could be extracted from the workflow checks + expectations above. For example, we could expect to match the hash of the ceremony artifacts stored in S3 and referenced on Firestore DB or verify the number of circuit documents in the ceremony subcollection, match data and info on the DB, verify rules paths on storage, and so on. 

Was that what you meant? I imagine that in the `ceremony_info.json` file in your pseudocode, there are (probably) details resulting from the database collections, and from those do the checks (like the examples above).

If you confirmed, I could start working on a set of checks that can be run with that data via a script (`verifyCeremony.sh`).

**Comment by 0xjei** [comment]
> 

Okay okay got it. Let's aim for something very easy to outline and implement too.
