### ISSUE TITLE
Evaluate MACI documentation needs

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#780]
As we try to re-invigorate the maintenance & documentation of this project (related to #728), I think it's worth re-evaluating our documentation needs in order to move forward with the best documentation platform possible.

Attempting to outline a list of needs for MACI documentation below.

**Documentation requirements:**
- support for markdown syntax (low barrier for contributions & all our docs are already in MD files)
- support for LaTex or similar for mathematical formulas (see #729)
- versioning (have heard anecdotal reports of user confusion on what MACI version or current docs refer to, e.g. v1.0 or v1.1) - we should have snapshots of our documentation for each MACI release that we support
- search functionality

**Documentation nice-to-haves:**
- open source solution
- ability to self-host
- preview deploy functionality (e.g. to easily review PRs that change the docs)
  - this may be something we can solve ourselves via GH actions or other workflows
- feedback collection (ability for visitors to submit feedback on if a docs page is helpful)
- easy ability to contribute (e.g. an "edit the page" button to GH repo)
- light & dark theme
- internationalization support

This list is likely incomplete - please feel free to add your input via comments below & I'll try to keep this updated based on community feedback! Once we have a clear set of requirements, let's align on solution.

**Potential documentation platforms:**
- [Docusauraus](https://docusaurus.io/)
- [GitBook](https://docs.gitbook.com/)
- [Read the docs](https://about.readthedocs.com/)
- [mdBook](https://rust-lang.github.io/mdBook/)
  - what we currently use, but unclear if it supports versioning

**Comment by a2468834** [comment]
Hello @samajammin 👋
I have the same feeling you told in #728.
Recently, I am starting to work on simplifying the docs first.
But I don't have any concrete roadmap or task list yet.

Besides, after chatting with one of contributor previously, I think we could use some LLM tools for evaluate the quality of docs (e.g, [LLM-Adapters](https://github.com/AGI-Edgerunners/LLM-Adapters)).

It's quite nice to hear other developer talking about the same issue.
Maybe we could discuss more and share the tasks in this issue together.

**Comment by yuetloo** [comment]
I would like to see more details on MACI integration.

* Circuit parameters
For example, if we use circuit [micro](https://github.com/privacy-scaling-explorations/maci/wiki/Precompiled-v1.1.1#micro-size), what version of MACI works with this circuit and if there's trusted setup.
What parameters to pass to the [setVerifyingKeys](https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/setVerifyingKeys.ts) and the [deployPoll](https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/deployPoll.ts) cli to use the (e.g. [micro](https://github.com/privacy-scaling-explorations/maci/wiki/Precompiled-v1.1.1#micro-size)) circuit.

* How to verify tally results on chain
The [verify](https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/verify.ts) cli only verifies tally results off-chain.

* Complete integration flow
Currently, the [integration guide](https://privacy-scaling-explorations.github.io/maci/integrating-maci.html) only talks about contributing and publishing messages.  Would like to see a more complete flow starting from deploying contracts, integrating with InitialVoiceCreditProxy, using the topup feature and the subsidy feature, finalizing, verifying on-chain, how to check in the contract if a poll was finalized.

* Cancel or reset poll
In [v0.10.1](https://github.com/privacy-scaling-explorations/maci/blob/v0.10.1/contracts/sol/MACI.sol#L670), there's coordinatorReset function to reset and redo the tally if tallying failed, (e.g., incorrect MACI logs being passed to the tally script). In v1, since there's no reset function, does it mean there's no option to cancel or reset a poll?

**Comment by samajammin** [comment]
Added Docusaurus as an option:
https://docusaurus.io/

They JUST released v3.0, which looks to have all the features we'd need:
https://docusaurus.io/blog/releases/3.0

I see Semaphore uses it as well:
https://github.com/semaphore-protocol/website
Might be nice to share resources/learnings on that front...

**Comment by samajammin** [comment]
Without having done much in-depth research across options, I like the look of Docusaurus:
- It supports all the requirements & nice-to-haves listed in the issue
- It appears to be well-maintained by Meta & they just released a [fresh new version](https://docusaurus.io/blog/releases/3.0)
- It seems highly customizable, e.g. to build [one-off pages](https://docusaurus.io/docs/creating-pages) or [a blog](https://docusaurus.io/docs/blog), so it seems we could easily extend this from purely dev documentation to a fully-fledged website as we have the time/resources to do that - I don't believe any other options I listed support that functionality
- It's used by other PSE teams (e.g. [Semaphore](https://github.com/semaphore-protocol/website/tree/main) & [Unirep](https://github.com/Unirep/Unirep/tree/main/packages/docs)), so could be nice to share resources/learnings on that front

I don't think this is something we need to sink much time into in terms of evaluating options, so I'd suggest we just role with that if @ctrlc03 @baumstern you folks don't have any questions/concerns. If you have a preference for another solution, please share!

**Comment by ctrlc03** [comment]
Completed #826
