### ISSUE TITLE
Document MACI versioning

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#807]
We should establish & document our approach to versioning for this project.

Here are my current thoughts (borrowing largely from @cedoor's [outline for Semaphore](https://hackmd.io/@cedoor/r1SD81cxo))... publishing on HackMD for ease of commenting:
https://hackmd.io/@samajammin/maci-versioning

Input welcome on this! Thank you in advance 🙏

**Comment by baumstern** [comment]
I'm on the lookout for an alternative to SemVer since [it's prone to errors](https://predr.ag/blog/semver-violations-are-common-better-tooling-is-the-answer/). At first glance, [HeadVer](https://github.com/line/headver) seems promising. There are also other options like [ComVer](https://gitlab.com/staltz/comver) and [CalVer](https://calver.org/) that I'm considering.
